# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: publish

on:
  push:
    branches: [develop]

  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'The updated registry version number.'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop

      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: 'v14.16.0'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@lubysoftware'

      - name: Configure Git
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"

      - run: yarn install --frozen-lockfile
      - run: yarn version --patch -m "new Release 📣"
      - run: yarn build:prod
      - run: git stash
      - run: npm version ${{ github.event.inputs.version }}
      - run: git push

      - name: Authenticate with the GitHub Package Registry

      # Publish to GitHub Packages
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
