name: publish
on:
  push:
    branches:
      - develop
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'The updated registry version number.'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop

      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: 'v14.17.0'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@lubysoftware'

      - name: Configure Git
        run: |
          git config user.email "${{ secrets.MAIL }}"
          git config user.name "${{ secrets.ACTOR }}"

      - run: yarn install --frozen-lockfile
      - run: yarn version --patch -m "new Release 📣"
      - run: yarn build:prod
      - run: git stash
      - run: npm version ${{ github.event.inputs.version }}
      - run: git push

      # Publish to GitHub Packages

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}
